import Head from "next/head";
import { FC, useState } from "react";
import { SelectedPage } from "~/mylinks/types";
import Navbar from "~/pages/a-navbar";
import Header from "~/pages/c-header";
import About from "./d-aboutme/about";
import Progress from "./e-progress/Progress";
import Contact from "./f-contact/ContactMe";
import Footer from "./g-footer/Footer";

const Home: FC & { isPublic?: boolean } = () => {

  const [selectedPage, setSelectedPage] = useState<SelectedPage>(SelectedPage.Home);

  return (
    <>
      <Head>
        <title>Rowell Is A God</title>
        <meta name="Portfolio" content="Generated By God's" />
        <link rel="icon" href="/Bart1.png" />
      </Head>
      
      {/*=======================> components <======================== */}
      <Navbar 
        selectedPage={selectedPage}
        setSelectedPage={setSelectedPage}
      />
      <Header 
        setSelectedPage={setSelectedPage}
      />
      <About 
        setSelectedPage={setSelectedPage}
      />
      <Progress 
        setSelectedPage={setSelectedPage}
      />
      <Contact 
        setSelectedPage={setSelectedPage}
      />
      <Footer />
    </>
  );
};

Home.isPublic = true;

export default Home;
